"""
Django settings for prodomia_app project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", default="django-insecure-dev-only-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG")

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    "corsheaders",
    "rest_framework",
    "drf_spectacular",

    # Local
    "condo_app",
    "payments",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prodomia_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prodomia_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#DATABASES = {
#    "default": env.db(
#        "DATABASE_URL",
#        default=f"sqlite:///{(BASE_DIR / 'db.sqlite3').as_posix()}",
#    )
#}

DATABASES = {
    "default": env.db("DATABASE_URL")
}

DATABASES["default"]["OPTIONS"] = {
    "sslmode": "require",
    "options": "-4",  # IPv4 session pooling supabase
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS / frontend dev server
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=["http://localhost:5173"],
)

# Transbank WebPay Plus
TRANSBANK_COMMERCE_CODE = env("TRANSBANK_COMMERCE_CODE", default="597055555532")
TRANSBANK_API_KEY = env(
    "TRANSBANK_API_KEY",
    default="579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C",
)
TRANSBANK_ENVIRONMENT = env("TRANSBANK_ENVIRONMENT", default="TEST")
TRANSBANK_RETURN_URL = env(
    "TRANSBANK_RETURN_URL",
    default="http://localhost:8000/api/payments/webpay/callback/",
)
FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:5173")

# Email (SMTP)
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="Prodomia <noreply@prodomia.cl>")
EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=10)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Prodomia API",
    "DESCRIPTION": (
        "API REST para la gestión de condominios.\n\n"
        "### Autenticación\n"
        "Todos los endpoints (excepto registro e inicio de sesión) requieren un **Bearer token** JWT.\n"
        "Obtén tu token en `POST /api/auth/token/` e inclúyelo en el header:\n"
        "```\nAuthorization: Bearer <access_token>\n```\n\n"
        "### Roles\n"
        "| Rol | Descripción |\n"
        "|-----|-------------|\n"
        "| `manager` | Administrador del condominio (acceso total). |\n"
        "| `staff` | Personal de mantención (ve reclamos asignados). |\n"
        "| `resident` | Residente (debe estar aprobado para operar). |"
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [{"jwtAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "jwtAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "ENUM_NAME_OVERRIDES": {
        "ComplaintStatusEnum": ["NEW", "ASSIGNED", "IN_PROGRESS", "RESOLVED", "REJECTED", "CLOSED"],
        "PaymentStatusEnum": ["PENDING", "PAID", "FAILED", "MANUAL"],
    },
    "TAGS": [
        {"name": "Autenticación", "description": "Registro, inicio de sesión y gestión de tokens JWT."},
        {"name": "Usuarios", "description": "Administración de usuarios del condominio (solo administrador)."},
        {"name": "Reclamos", "description": "Gestión de reclamos y solicitudes del condominio."},
        {"name": "Cuotas", "description": "Cuotas mensuales por unidad residencial."},
        {"name": "Pagos", "description": "Pagos online vía WebPay Plus y registros manuales."},
        {"name": "Anuncios", "description": "Anuncios y comunicados del condominio."},
        {"name": "Dashboard", "description": "Estadísticas generales para el administrador."},
    ],
}
